# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17cd521d548a61e959ffd4c9361228eec0be7638dee40723129b3ab767e949d1ae8d9ed3436bca9ecfb55f16cd7d4a6f533fcbe3807c404a43abd91c53b84999

test:
  secret_key_base: 334c6bdc301d3081ad2a7aa1034530f16e320f25ef7161763a096c2caa209dc6f1d26edb67af1169ed58ed7d205bfc37a5107bb732b9a5c864052bc08683acc8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
